"""Additional publication pages. Receives the site's shared rendering functions."""
import json,re,html

def build(ctx):
    page,section,SRC,ROOT,REL=[ctx[k] for k in ('page','section','SRC','ROOT','REL')]
    esc=html.escape
    def raw(path,label):return f'<a href="/dh-adom/source/{path}">{label}</a>'
    tests='04-Reference-Implementation/tests/test_core.py'
    evidence=[
      ('Artifact only','03-Reference-Templates/ENGINEERING_CONSTITUTION.md','Constitution template exists; precedence enforcement is not exercised.','Attempt a conflicting action and retain its rejection record.'),
      ('Partial demonstration','04-Reference-Implementation/examples/demo.py','The demo registers an identifiable Root agent.','Bind the actual coordinator to a durable identity record.'),
      ('Partial demonstration',tests,'The routing test looks up one feature owner.','Test missing and duplicate owners across all registered domains.'),
      ('Partial demonstration','04-Reference-Implementation/dh_adom/policy.py','Declared limits are compared; live runtime limits are not metered.','Exercise depth, cost, time, tool and scope boundaries.'),
      ('Partial demonstration','04-Reference-Implementation/dh_adom/models.py','A contract model and in-memory event references exist.','Persist complete contracts and verify retrieval by delegation ID.'),
      ('Manual validation required','03-Reference-Templates/ROOT_AGENT.md','The role template defines coordination expectations.','Attempt a Root write across a feature boundary without approval.'),
      ('Manual validation required','03-Reference-Templates/ENGINEERING_CONSTITUTION.md','No software-lifecycle transition test is supplied.','Trace a real task through each required lifecycle gate.'),
      ('Model only','02-Specification/State-Machines/agent-lifecycle.mermaid','Lifecycle states are specified, not enforced by the demo.','Reject an invalid transition and record the governing policy.'),
      ('Partial demonstration','04-Reference-Implementation/dh_adom/models.py','Agent identity is modeled separately from provider/model choice.','Demonstrate an identity surviving a model change.'),
      ('Partial demonstration',tests,'Permission escalation is rejected in one supplied test.','Test all enabled tools and environments against delegated permissions.'),
      ('Partial demonstration','04-Reference-Implementation/dh_adom/policy.py','Step and cost declarations are checked against parent limits.','Measure consumption; stop execution at each actual budget limit.'),
      ('Manual validation required','04-Reference-Implementation/dh_adom/policy.py','Declared depth is checked; recursion and parallelism are not enforced.','Apply repeated spawn pressure and verify hard termination limits.'),
      ('Manual validation required','04-Reference-Implementation/dh_adom/models.py','Handoff records are modeled; persistence is host responsibility.','Restart the host and recover complete state and handoff records.'),
      ('Manual validation required','07-Architecture-Diagrams/svg/07-traceability.svg','The figure describes traceability; no end-to-end assertion is supplied.','Resolve a requirement through task, change, test and release IDs.'),
      ('Partial demonstration','04-Reference-Implementation/dh_adom/audit.py','In-memory demo events exist; durable and denied-action audit is absent.','Record allowed and denied actions in tamper-resistant durable storage.'),
      ('Manual validation required','03-Reference-Templates/DELEGATION_CONTRACT.yaml','The template expresses include/exclude boundaries.','Reject a cross-domain write without explicit coordination.'),
      ('Manual validation required','02-Specification/State-Machines/delegation-lifecycle.mermaid','Failure and timeout states are modeled; no scheduler is bundled.','Inject timeout and tool failure; verify stop, cleanup and handoff.'),
      ('Manual validation required','03-Reference-Templates/FEATURE_AGENT.md','No fresh-session recovery experiment is included.','Resume in an independent session using persisted artifacts only.'),
      ('Manual validation required','04-Reference-Implementation/dh_adom/agents.py','The deterministic specialist returns COMPLETE without an evidence gate.','Reject completion when required validation evidence is missing.'),
      ('Partial demonstration',tests,'The supplied tests are repeatable; full conformance evidence is absent.','Publish environment, commands and results for all requirements.')]
    requirements=[]
    for line in (SRC/'02-Specification/CONFORMANCE-REQUIREMENTS.md').read_text().splitlines():
        if line.startswith('| CR-'):
            ident,req,severity=[x.strip() for x in line.strip('|').split('|')]
            status,source,observed,validate=evidence[len(requirements)]
            requirements.append(dict(id=ident,requirement=req,severity=severity,status=status,source=source,observed=observed,validation=validate))
    (SRC/'05-Conformance-Validation-Suite/coverage.json').write_text(json.dumps({'edition':'1.1.0','scope':'Review mapping, not a certification or complete test result','requirements':requirements},indent=2),encoding='utf-8')
    rows=''.join(f'<tr id="{r["id"].lower()}"><th scope="row">{r["id"]}</th><td>{esc(r["requirement"])}<br><small>{r["severity"]}</small></td><td>{r["status"]}</td><td>{esc(r["observed"])}<br>{raw(r["source"],"Inspect artifact")}</td><td>{esc(r["validation"])}</td></tr>' for r in requirements)
    page('conformance','A requirement is only as strong as its evidence.', 'Inspect all 20 requirements, the evidence in the supplied reference package, and the validation an adopter needs to perform.',section('How to read this assessment.','<p>This is a source-review coverage map. “Partial demonstration” means only part of a requirement is illustrated. A file-presence check is not proof that a control works. No complete-conformance or certification claim is made.</p><p>The specification requires mandatory requirements to be satisfied or formally excepted; the requirements list distinguishes Critical and High priority. Record the interpretation, responsible approver and any accepted exception with your assessment.</p>')+'<div class="dh-table" tabindex="0" aria-label="Scrollable conformance evidence table"><table class="dh-conformance"><thead><tr><th>ID</th><th>Requirement</th><th>Coverage</th><th>Evidence in this release</th><th>Adopter validation</th></tr></thead><tbody>'+rows+'</tbody></table></div>'+section('Reproduce and extend.',raw('05-Conformance-Validation-Suite/coverage.json','Download the coverage map / JSON')+'<p>Run the included Python unit tests and file-presence script from the extracted package. Then add host-level tests for the controls above. Preserve your environment, version, outputs and exceptions alongside the evidence.</p>'))
    schemas=[]
    for p in sorted((SRC/'02-Specification/Schema-Definitions').glob('*.json')):
        data=json.loads(p.read_text());required=', '.join(data.get('required',[]))
        schemas.append('<div class="dh-card"><h2>'+esc(data['title'])+'</h2><p>Required top-level fields: <code>'+esc(required)+'</code>.</p>'+raw('02-Specification/Schema-Definitions/'+p.name,'Open JSON Schema →')+'</div>')
    page('schemas','Contracts you can inspect directly.', 'Read the supplied JSON Schemas, delegation template, lifecycle models and API outline without unpacking the full release.', '<div class="dh-grid">'+''.join(schemas)+'</div>'+section('Validation scope.','<p>These schemas validate the supplied structural contract. Several nested objects remain permissive, and numeric budgets do not yet carry minimum constraints. Schema acceptance alone is not authorization or full conformance. Apply policy checks and runtime enforcement independently.</p>')+section('Delegation and lifecycle.',raw('03-Reference-Templates/DELEGATION_CONTRACT.yaml','Delegation contract / YAML')+'<ul>'+''.join('<li>'+raw('02-Specification/State-Machines/'+name+'-lifecycle.mermaid',name.title()+' lifecycle / Mermaid')+'</li>' for name in ('agent','delegation','feature'))+'</ul>')+section('API outline.', '<p>The OpenAPI document sketches agent registration, delegation and audit retrieval. It does not define complete request/response schemas, authentication or a running service.</p>'+raw('02-Specification/API-Definitions/openapi.yaml','OpenAPI 3.1 outline / YAML')))
    page('adoption','Start with one bounded engineering task.', 'Use the reference package to explore the method, establish ownership and collect evidence before expanding its scope.',section('1. Understand the component terms.','<p>The reference code carries Apache-2.0 terms. The paper, templates and diagrams retain separate research-and-evaluation terms. Check the <a href="/dh-adom/downloads/">component notices</a> before adapting or redistributing material for a business deployment.</p>')+section('2. Run the reference example.','<p>Download publication package 1.1.0, extract it, and open a terminal in <code>DH-ADOM/04-Reference-Implementation</code>. Python 3.11 or later is required; the demo uses the standard library.</p><pre>python -m unittest discover -s tests -v\npython -m examples.demo</pre><p>Expected: three tests pass; the deterministic demo returns <code>TASK-DEMO</code> with status <code>COMPLETE</code> and four audit events. This verifies the supplied example only.</p>')+section('3. Map ownership and authority.','<p>Choose one repository area and identify its feature owner. Record the Root coordinator, allowed paths, tools and permissions. Define what requires human approval and what is explicitly out of scope.</p><p>'+raw('03-Reference-Templates/ENGINEERING_CONSTITUTION.md','Read the constitution template')+' · '+raw('03-Reference-Templates/FEATURE_AGENT.md','Read the feature-role template')+'</p>')+section('4. Specify a reviewable task.','<p>Use the delegation contract to record the parent, child, task, include/exclude paths, budget, lifetime, evidence and acceptance criteria. Keep execution in an isolated development environment until the host controls are validated.</p>')+section('5. Require evidence before accepting work.','<p>Record changed files, tests, outputs and unresolved risks. Have the feature owner review the handoff. Test cross-domain coordination and fresh-session recovery with persisted state.</p>')+section('6. Assess and share reproducible evidence.','<p>Work through the <a href="/dh-adom/conformance/">20-requirement coverage map</a>. Compare outcomes using the <a href="/dh-adom/evaluation/">evaluation protocol</a>; keep task sets, environments, raw results and human interventions. Remove credentials and private repository data before sharing.</p><p><a href="/contact/">Discuss an adoption or research evaluation →</a></p>'))
    # Append a specific threat model to the existing security page.
    threats=[('Prompt injection','Tool output or repository text tries to redirect an agent.','Treat external content as data; authorize actions independently of model text.'),('Context poisoning','A handoff supplies false goals, approvals or results.','Validate provenance, scope and evidence before resuming.'),('Impersonation','An agent claims a trusted role or parent identity.','Bind identities to host authentication and verified delegation records.'),('Privilege escalation','A child requests tools or paths beyond its contract.','Intersect delegated permissions with host policy; reject self-escalation.'),('Scope confusion','A task crosses another feature owner’s boundary.','Enforce path and resource boundaries; require cross-feature review.'),('Recursive delegation','Repeated spawning exhausts time, cost or workers.','Meter depth, concurrency and runtime; enforce termination.'),('Audit manipulation','Actions or outcomes are omitted or rewritten.','Use durable append-only audit storage with access controls.'),('Tool abuse','An authorized tool performs unintended external effects.','Mediate side effects; require approval for consequential operations.'),('Stale state','Old ownership or policy records drive new decisions.','Version state and verify freshness before authorization.'),('Root or Feature compromise','A coordinator misuses its authority across its governed scope.','Constrain coordinator privileges and use independent approval and revocation.')]
    content=section('Threat model and trust boundaries.','<p>Protected assets include repository integrity, credentials, external systems, budgets and evidence. Trust boundaries separate user intent, model output, repository content, delegated agents, the host authorizer, tools and durable audit storage. The following are design controls to implement and test in the host; the demo does not enforce the complete model.</p><div class="dh-table"><table><thead><tr><th>Threat</th><th>Failure mode</th><th>Control to validate</th></tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(c)+'</td>' for c in r)+'</tr>' for r in threats)+'</tbody></table></div>')
    path=ROOT/'dh-adom/security/index.html';s=path.read_text(encoding='utf-8');s=s.replace('<aside class="dh-source">',content+'<aside class="dh-source">');path.write_text(s,encoding='utf-8')
    glossary=[('Bounded engineering domain','A registered ownership area with explicit repository paths or resources and a named owner.'),('Material work or meaningful task','Work that changes behavior, repository artifacts, permissions or externally observable state; define local thresholds in governance.'),('Production action','An operation affecting a live environment, user data or an external system beyond an isolated evaluation.'),('Explicit authorization','A traceable approval bound to an identity, task, scope, policy version and validity period.'),('Accepted exception','A documented deviation with rationale, owner, approval, scope and expiry; report it alongside assessment results.')]
    section_html=section('Adoption glossary · informative.','<p>These operational interpretations help adopters make the specification testable. They are guidance, not amendments to the version 1.0 normative text.</p><dl>'+''.join('<dt><strong>'+a+'</strong></dt><dd>'+b+'</dd>' for a,b in glossary)+'</dl><p><a href="/dh-adom/conformance/">Review conformance evidence →</a></p>')
    path=ROOT/'dh-adom/specification/index.html';s=path.read_text(encoding='utf-8');s=s.replace('<aside class="dh-source">',section_html+'<aside class="dh-source">');path.write_text(s,encoding='utf-8')
    comparison=section('Where DH-ADOM fits.','<p>This is a comparison of focus, not a claim that other approaches lack a capability. Implementations and products vary.</p><div class="dh-table"><table><thead><tr><th>Approach</th><th>Documented focus</th><th>Relationship to DH-ADOM</th></tr></thead><tbody><tr><th>Orchestrator-worker patterns</th><td>Decompose tasks, delegate work and synthesize results.</td><td>Execution pattern used within an ownership model. <a href="https://www.anthropic.com/engineering/building-effective-agents">Anthropic</a></td></tr><tr><th>AI-SDLC</th><td>Lifecycle orchestration, governance, policy and engineering gates.</td><td>Lifecycle governance informs the work of owned engineering domains. <a href="https://ai-sdlc.io/docs/spec/primer">Framework primer</a></td></tr><tr><th>ADLC</th><td>Design, develop, validate, deploy and monitor agents.</td><td>Agent lifecycle responsibilities apply to the hierarchy. <a href="https://architect.salesforce.com/docs/architect/fundamentals/guide/agent-development-lifecycle">Salesforce Architects</a></td></tr><tr><th>DH-ADOM</th><td>Repository ownership, bounded delegation and evidence-backed handoff.</td><td>An organizational method to apply alongside lifecycle governance and execution tools.</td></tr></tbody></table></div>')
    path=ROOT/'dh-adom/research/index.html';s=path.read_text(encoding='utf-8');s=s.replace('<aside class="dh-source">',comparison+'<aside class="dh-source">');path.write_text(s,encoding='utf-8')
